# Generated by Django 4.2.6 on 2026-04-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='manufacturer_partner',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='service_centre_place',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='service_centre_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
