# Generated by Django 4.2.6 on 2026-02-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('EMERGENCY_DELAY', 'Mechanic Not Arriving On Time'), ('SERVICE_QUALITY', 'Poor Service Quality'), ('PAYMENT_ISSUE', 'Payment Dispute'), ('OTHER', 'Other')], default='EMERGENCY_DELAY', max_length=20),
        ),
    ]
