# Generated by Django 4.2.6 on 2026-04-10 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='preferred_mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
