# Generated by Django 4.2.6 on 2026-04-22 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_preferred_mechanic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=20, unique=True)),
                ('bill_type', models.CharField(choices=[('ADVANCE', 'Advance Payment'), ('FINAL', 'Final Payment')], max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin_commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('admin_commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mechanic_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('mechanic_name', models.CharField(blank=True, max_length=200)),
                ('mechanic_email', models.EmailField(blank=True, max_length=254)),
                ('vehicle_name', models.CharField(max_length=200)),
                ('service_type', models.CharField(max_length=50)),
                ('service_details', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='bookings.booking')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='bookings.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
